---
abstract: "RWSTAUNER's Dist::Zilla config"
author:
  - 'Randy Stauner <rwstauner@cpan.org>'
build_requires:
  Dist::Zilla::Role::Plugin: 0
  Dist::Zilla::Role::Releaser: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::DZil: 0
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-RWSTAUNER
no_index:
  directory:
    - corpus
    - examples
    - inc
    - share
    - t
    - xt
  namespace:
    - Local
    - t::lib
  package:
    - DB
provides:
  Dist::Zilla::PluginBundle::Author::RWSTAUNER:
    file: lib/Dist/Zilla/PluginBundle/Author/RWSTAUNER.pm
    version: 3.203
  Pod::Weaver::PluginBundle::Author::RWSTAUNER:
    file: lib/Pod/Weaver/PluginBundle/Author/RWSTAUNER.pm
    version: 3.203
recommends:
  Dist::Zilla::Plugin::Test::PodSpelling: 2
requires:
  Dist::Zilla: 4.200005
  Dist::Zilla::Plugin::Authority: 1.005
  Dist::Zilla::Plugin::Bootstrap::lib: 0
  Dist::Zilla::Plugin::Bugtracker: 0
  Dist::Zilla::Plugin::CheckChangesHasContent: 0.003
  Dist::Zilla::Plugin::CheckExtraTests: 0
  Dist::Zilla::Plugin::CopyReadmeFromBuild: 0.0019
  Dist::Zilla::Plugin::DualBuilders: 1.001
  Dist::Zilla::Plugin::Git::NextVersion: 0
  Dist::Zilla::Plugin::GithubMeta: 0.10
  Dist::Zilla::Plugin::InstallRelease: 0.006
  Dist::Zilla::Plugin::MetaNoIndex: 1.101130
  Dist::Zilla::Plugin::MetaProvides::Package: 1.11044404
  Dist::Zilla::Plugin::MinimumPerl: 0.02
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::Prepender: 1.112280
  Dist::Zilla::Plugin::ReadmeMarkdownFromPod: 0.103510
  Dist::Zilla::Plugin::ReportVersions::Tiny: 1.01
  Dist::Zilla::Plugin::Repository: 0.16
  Dist::Zilla::Plugin::Run: 0.008
  Dist::Zilla::Plugin::TaskWeaver: 0.101620
  Dist::Zilla::PluginBundle::Basic: 0
  Dist::Zilla::PluginBundle::Git: 1.110500
  Dist::Zilla::PluginBundle::TestingMania: 0.014
  Dist::Zilla::Role::PluginBundle::Config::Slicer: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Dist::Zilla::Role::PluginBundle::PluginRemover: 0
  Dist::Zilla::Stash::PodWeaver: 1.001000
  List::Util: 0
  Moose: 0
  Moose::Util::TypeConstraints: 1.01
  Pod::Elemental: 0.102360
  Pod::Elemental::Transformer::List: 0
  Pod::Markdown: 1.120
  Pod::Weaver: 3.101632
  Pod::Weaver::Config::Assembler: 0
  Pod::Weaver::Plugin::StopWords: 1.001005
  Pod::Weaver::Plugin::Transformer: 0
  Pod::Weaver::Plugin::WikiDoc: 0
  Pod::Weaver::PluginBundle::Default: 0
  Pod::Weaver::Section::Support: 1.001
  YAML::Tiny: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-Author-RWSTAUNER
  homepage: https://github.com/rwstauner/Dist-Zilla-PluginBundle-Author-RWSTAUNER
  repository: https://github.com/rwstauner/Dist-Zilla-PluginBundle-Author-RWSTAUNER.git
version: 3.203
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::RWSTAUNER/Git::NextVersion'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::GenerateFile
      name: '@Author::RWSTAUNER/GenerateManifestSkip'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::RWSTAUNER/GatherDir'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::RWSTAUNER/PruneCruft'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::RWSTAUNER/ManifestSkip'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Author::RWSTAUNER/PruneDevelCoverDatabase'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Author::RWSTAUNER/PruneCodeStatCollection'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::RWSTAUNER/Authority'
      version: 1.005
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::RWSTAUNER/NextRelease'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::RWSTAUNER/PkgVersion'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Author::RWSTAUNER/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::RWSTAUNER/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::RWSTAUNER/License'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::ReadmeMarkdownFromPod
      name: '@Author::RWSTAUNER/ReadmeMarkdownFromPod'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::CopyReadmeFromBuild
      name: '@Author::RWSTAUNER/CopyReadmeFromBuild'
      version: 0.0019
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Author::RWSTAUNER/Bugtracker'
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Author::RWSTAUNER/Repository'
      version: 0.18
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::RWSTAUNER/GithubMeta'
      version: 0.28
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::RWSTAUNER/AutoPrereqs'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Author::RWSTAUNER/MetaNoIndex'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Author::RWSTAUNER/MetaProvides::Package'
      version: 1.12060501
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::RWSTAUNER/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::RWSTAUNER/MetaConfig'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::RWSTAUNER/MetaYAML'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::RWSTAUNER/MetaJSON'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::RWSTAUNER/ExecDir'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::RWSTAUNER/ShareDir'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Author::RWSTAUNER/ModuleBuild'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::RWSTAUNER/MakeMaker'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::DualBuilders
      name: '@Author::RWSTAUNER/DualBuilders'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::RWSTAUNER/ReportVersions::Tiny'
      version: 1.03
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@Author::RWSTAUNER/Test::PodSpelling'
      version: 2.001002
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: '@Author::RWSTAUNER/@TestingMania/Test::UnusedVars'
      version: 2.0.1
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@Author::RWSTAUNER/@TestingMania/Test::Portability'
      version: 2.0.2
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@Author::RWSTAUNER/@TestingMania/Test::Version'
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::RWSTAUNER/@TestingMania/PodCoverageTests'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::RWSTAUNER/@TestingMania/Test::Perl::Critic'
      version: 2.112410
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::RWSTAUNER/@TestingMania/Test::CPAN::Changes'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@Author::RWSTAUNER/@TestingMania/Test::CPAN::Meta::JSON'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Author::RWSTAUNER/@TestingMania/Test::DistManifest'
      version: 2.0.1
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::RWSTAUNER/@TestingMania/MetaTests'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Author::RWSTAUNER/@TestingMania/Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: '@Author::RWSTAUNER/@TestingMania/Test::Kwalitee'
      version: 2.03
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Author::RWSTAUNER/@TestingMania/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::RWSTAUNER/@TestingMania/Test::MinimumVersion'
      version: 2.0.1
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: '@Author::RWSTAUNER/@TestingMania/Test::Pod::LinkCheck'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::RWSTAUNER/@TestingMania/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::RWSTAUNER/@TestingMania/PodSyntaxTests'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: '@Author::RWSTAUNER/@TestingMania/MojibakeTests'
      version: 0.3
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::RWSTAUNER/Manifest'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@Author::RWSTAUNER/CheckExtraTests'
      version: 0.004
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@Author::RWSTAUNER/CheckChangesHasContent'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::RWSTAUNER/TestRelease'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::RWSTAUNER/@Git/Check'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::RWSTAUNER/@Git/Commit'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::RWSTAUNER/@Git/Tag'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::RWSTAUNER/@Git/Push'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::RWSTAUNER/ConfirmRelease'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::RWSTAUNER/UploadToCPAN'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::RWSTAUNER/InstallRelease'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: RuntimeRequires
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: recommends
      name: RuntimeRecommends
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300003
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300003
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300003
x_authority: cpan:RWSTAUNER
